create table if not exists public.cakes(id bigint generated by default as identity primary key,name text not null,image_url text not null,price_500 numeric not null default 0,price_1000 numeric not null default 0,available boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.admins(user_id uuid primary key references auth.users(id) on delete cascade,created_at timestamptz not null default now());
alter table public.cakes enable row level security; alter table public.admins enable row level security;
create policy "public view cakes" on public.cakes for select to anon,authenticated using(true);
create policy "admin insert cakes" on public.cakes for insert to authenticated with check(exists(select 1 from public.admins a where a.user_id=auth.uid()));
create policy "admin update cakes" on public.cakes for update to authenticated using(exists(select 1 from public.admins a where a.user_id=auth.uid())) with check(exists(select 1 from public.admins a where a.user_id=auth.uid()));
create policy "admin delete cakes" on public.cakes for delete to authenticated using(exists(select 1 from public.admins a where a.user_id=auth.uid()));
create policy "admin read own record" on public.admins for select to authenticated using(user_id=auth.uid());
create policy "public view cake images" on storage.objects for select to anon,authenticated using(bucket_id='cake-images');
create policy "admin upload cake images" on storage.objects for insert to authenticated with check(bucket_id='cake-images' and exists(select 1 from public.admins a where a.user_id=auth.uid()));
create policy "admin update cake images" on storage.objects for update to authenticated using(bucket_id='cake-images' and exists(select 1 from public.admins a where a.user_id=auth.uid())) with check(bucket_id='cake-images' and exists(select 1 from public.admins a where a.user_id=auth.uid()));
create policy "admin delete cake images" on storage.objects for delete to authenticated using(bucket_id='cake-images' and exists(select 1 from public.admins a where a.user_id=auth.uid()));
-- after creating Rashi Auth user:
-- insert into public.admins(user_id) values('USER_UUID_HERE');
